import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  sidebar305ap: [
    {
      type: 'category',
      label: '305ap',
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: '.' }],
    },
  ],
};

export default sidebars;
